CREATE TABLE IF NOT EXISTS contacts( 
	contact_id BIGSERIAL NOT NULL PRIMARY KEY,
	date_time TIMESTAMP NOT NULL,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL,
	cog FLOAT,
	heading FLOAT NOT NULL,
	depth INT,
	knots DOUBLE PRECISION
);